### ISSUE TITLE
Getting errors trying to compile using VS2019

### ISSUE THREAD

**Issue by c3rberus** [MikePohatu/DevChecker#1]
Using VS2019 trying to compile from source, I get..

C:\Users\x\Source\Repos\DevChecker\source\Tests\PoshTests.cs(38,43,38,52): error CS0117: 'PoshHandler' does not contain a definition for 'GetRunner'
C:\Users\x\Source\Repos\DevChecker\source\Tests\PoshTests.cs(39,85,39,89): error CS1503: Argument 1: cannot convert from 'System.Management.Automation.PowerShell' to 'bool'
C:\Users\x\Source\Repos\DevChecker\source\Tests\PoshTests.cs(63,43,63,52): error CS0117: 'PoshHandler' does not contain a definition for 'GetRunner'
C:\Users\x\Source\Repos\DevChecker\source\Tests\PoshTests.cs(65,86,65,90): error CS1503: Argument 1: cannot convert from 'System.Management.Automation.PowerShell' to 'bool'

Do I need some additional packages installed in VS to compile?

**Comment by MikePohatu** [comment]
Fixed with commit 9d31da615557bc5601bbfe01074af7540f3be435. Test wasn't updated after I made changes to the PoshHandler and a VS update broke something so it wasn't throwing errors. Fixed now.

**Comment by c3rberus** [comment]
Thanks that fixed it.
