### ISSUE TITLE
Feature request: List and uninstall programs remotely?

### ISSUE THREAD

**Issue by c3rberus** [MikePohatu/DevChecker#2]
Similar to the hotfix tab for windows updates, it would be great to add another tab that lists installed programs and the ability to remotely uninstall them.

There are two places to pull the UninstallString for msiexec:

Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
Microsoft\Windows\CurrentVersion\Uninstall

This link goes into detail with PoSh example... 
https://stackoverflow.com/questions/113542/how-can-i-uninstall-an-application-using-powershell

**Comment by MikePohatu** [comment]
Added in commit 0aaf8820e2ff86bf853cca8f9b5877d4e7deb694. Only supports MSI uninstalls as other methods have too many permutations and can't guarantee a silent/unattended uninstall.
